CREATE TABLE `address_standard_approval`
(
    `id`                 bigint       NOT NULL COMMENT '申请单ID',
    `apply_no`           varchar(64)  NOT NULL COMMENT '申请单号',
    `operation_type`     varchar(32)  NOT NULL COMMENT '操作类型',
    `flow_code`          varchar(64)  NOT NULL COMMENT '流程编码',
    `business_status`    varchar(32)  DEFAULT NULL COMMENT 'workflow业务状态',
    `approval_status`    varchar(32)  DEFAULT NULL COMMENT '审批状态',
    `instance_id`        bigint       DEFAULT NULL COMMENT '流程实例ID',
    `current_task_id`    bigint       DEFAULT NULL COMMENT '当前任务ID',
    `biz_title`          varchar(255) DEFAULT NULL COMMENT '业务标题',
    `source_summary`     varchar(1000) DEFAULT NULL COMMENT '原地址摘要',
    `target_summary`     varchar(1000) DEFAULT NULL COMMENT '新地址摘要',
    `source_snapshot`    longtext     DEFAULT NULL COMMENT '原地址快照JSON',
    `target_snapshot`    longtext     DEFAULT NULL COMMENT '新地址快照JSON',
    `request_payload`    longtext     DEFAULT NULL COMMENT '请求参数JSON',
    `submit_fingerprint` varchar(64)  DEFAULT NULL COMMENT '提交内容指纹',
    `submit_guard_key`   varchar(64)  NOT NULL DEFAULT 'ACTIVE' COMMENT '重复提交保护占位键',
    `import_batch_payload` longtext   DEFAULT NULL COMMENT '导入批次JSON',
    `submit_user_id`     bigint       DEFAULT NULL COMMENT '提交人ID',
    `submit_user_name`   varchar(64)  DEFAULT NULL COMMENT '提交人账号',
    `submit_dept_id`     bigint       DEFAULT NULL COMMENT '提交部门ID',
    `submit_dept_name`   varchar(128) DEFAULT NULL COMMENT '提交部门名称',
    `approve_user_id`    bigint       DEFAULT NULL COMMENT '审批人ID',
    `approve_user_name`  varchar(64)  DEFAULT NULL COMMENT '审批人名称',
    `approve_time`       datetime     DEFAULT NULL COMMENT '审批时间',
    `reject_reason`      varchar(1000) DEFAULT NULL COMMENT '驳回原因',
    `execute_message`    varchar(1000) DEFAULT NULL COMMENT '执行信息',
    `create_dept`        bigint       DEFAULT NULL COMMENT '创建部门',
    `create_by`          bigint       DEFAULT NULL COMMENT '创建者',
    `create_time`        datetime     DEFAULT NULL COMMENT '创建时间',
    `update_by`          bigint       DEFAULT NULL COMMENT '更新者',
    `update_time`        datetime     DEFAULT NULL COMMENT '更新时间',
    `del_flag`           char(1)      DEFAULT '0' COMMENT '删除标志',
    PRIMARY KEY (`id`),
    KEY `idx_addr_std_approval_submit_user` (`submit_user_id`),
    KEY `idx_addr_std_approval_status` (`approval_status`),
    KEY `idx_addr_std_approval_task` (`current_task_id`),
    KEY `idx_addr_std_approval_instance` (`instance_id`),
    UNIQUE KEY `uk_addr_std_approval_submit_guard` (`submit_user_id`, `operation_type`, `submit_fingerprint`, `submit_guard_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标准地址审批申请单';
